# Run Travis CI for R using https://eddelbuettel.github.io/r-travis/

language: c

sudo: required

dist: trusty

before_install:
  - curl -OLs https://eddelbuettel.github.io/r-travis/run.sh && chmod 0755 run.sh
  - ./run.sh bootstrap

install:
  - ./run.sh install_aptget r-cran-rcpp r-cran-knitr r-cran-rmarkdown r-cran-dplyr r-cran-data.table r-cran-rapiserialize r-cran-qs && ./run.sh install_github traversc/stringfish

script:
  - ./run.sh run_tests && free -h && Rscript tests/tests.r && free -h
  
after_failure:
  - ./run.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change
