# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_string_type <- function(x) {
    .Call(`_stringfish_get_string_type`, x)
}

materialize <- function(x) {
    .Call(`_stringfish_materialize`, x)
}

sf_vector <- function(len) {
    .Call(`_stringfish_sf_vector`, len)
}

sf_assign <- function(x, i, e) {
    invisible(.Call(`_stringfish_sf_assign`, x, i, e))
}

sf_iconv <- function(x, from, to) {
    .Call(`_stringfish_sf_iconv`, x, from, to)
}

convert_to_sf <- function(x) {
    .Call(`_stringfish_convert_to_sf`, x)
}

sf_nchar <- function(x, type = "chars") {
    .Call(`_stringfish_sf_nchar`, x, type)
}

sf_substr <- function(x, start, stop) {
    .Call(`_stringfish_sf_substr`, x, start, stop)
}

c_sf_paste <- function(dots, sep) {
    .Call(`_stringfish_c_sf_paste`, dots, sep)
}

sf_collapse <- function(x, collapse) {
    .Call(`_stringfish_sf_collapse`, x, collapse)
}

sf_readLines <- function(file, encoding = "UTF-8") {
    .Call(`_stringfish_sf_readLines`, file, encoding)
}

sf_grepl <- function(subject, pattern, encode_mode = "auto") {
    .Call(`_stringfish_sf_grepl`, subject, pattern, encode_mode)
}

sf_gsub <- function(subject, pattern, replacement, encode_mode = "auto") {
    .Call(`_stringfish_sf_gsub`, subject, pattern, replacement, encode_mode)
}

random_strings <- function(N, string_size = 50L, charset = "abcdefghijklmnopqrstuvwxyz", vector_mode = "stringfish") {
    .Call(`_stringfish_random_strings`, N, string_size, charset, vector_mode)
}

